### ISSUE TITLE
Change the workflow to run ci tests after a confirmation from the UI

### ISSUE THREAD

**Issue by ahsimb** [exasol/sagemaker-extension#132]
This should be similar to how it is done in other repos, for instance in [python-extension-common](https://github.com/exasol/python-extension-common).

* [x] @ahsimb will mark slow tests with `@pytest.mark.slow` in the context of [#119](119) and [#120](120), resulting in 2 categories of tests: 
  * C1) fast tests and 
  * C2) slow tests 
* [x] @ckunki will update the GitHub workflows to execute 
  * the fast tests on each `pull_request` and 
  * the slow ones only if manually confirmed. 
* [ ] Update Branch protection for Branch `main` to allow merging only if all tests have been executed and terminated successfully 
  * CI / Gate 1 - Regular CI 
  * CI / Gate 2 - Allow Merge

**Comment by ckunki** [comment]
Blocked by issue #120  
PR #121

**Comment by ckunki** [comment]
unblocked.
