### ISSUE TITLE
Get details of the polled Autopilot job status

### ISSUE THREAD

**Issue by umitbuyuksahin** [exasol/sagemaker-extension#20]
- Current polling implementation just provides general job statuses such as _FeatureEngineering_, _Training_, ...
- Get details of job status, e.g. in case of failure state the reason by following below steps:

1. call DescribeTrainingJobResponse
2. check FailureReason field

**Comment by redcatbear** [comment]
@umitbuyuksahin, make the issue title and description more precise.
