### ISSUE TITLE
Implement PredictionUDF using api-endpoint

### ISSUE THREAD

**Issue by tkilias** [exasol/sagemaker-extension#22]
# Background
- The extension only gets useful with prediction from Exasol
- Question:
  1. Do we create UDF per Model, TrainingJob (preferred) 
    - possible to hard code model specific things, like model connection object name
      - the connection object can be changed without changing the UDF 
    - you can do proper typing -> proper types Input and output variables 
  2. use generic UDF, where you variadic parameters
- Option 1. requires a  Luascript which create the UDF, connection object and the api endpoint 
- How to shut down and resume endpoint?

**Comment by umitbuyuksahin** [comment]
Reads connection object

- if "Not running" then Error("Endpoint not running")
- else send data for prediction
