### ISSUE TITLE
Handle prediction of uncompleted Autopilot job

### ISSUE THREAD

**Issue by umitbuyuksahin** [exasol/sagemaker-extension#32]
- if a job is interrupted before completion due to working of one of the "max_runtime" stopping criteria, autopilot might have several candidate but might not have an best candidate. 
- we can throw an exception saying that there is not a best candidate.

**Comment by exa-eswar** [comment]
"max_runtime" is one of the criteria to not select the best candidate. It would be helpful for user to understand what to do inorder to get best candidate. 
e.g.: If is it max_runtime error, throwing an exception to increase the max_runtime, also showing the current max_runtime would be helpful.
