### ISSUE TITLE
Add Autopilot endpoint information into Metadata table

### ISSUE THREAD

**Issue by umitbuyuksahin** [exasol/sagemaker-extension#35]
- keep SageMaker Autopilot endpoint information in the metadata row of the relevant model. So that users can keep track of which model is deployed and details of the endpoint such as the endpoint-name.
- Discuss how to update a row when an endpoint is created/deleted.

**Comment by redcatbear** [comment]
@umitbuyuksahin , please specify which endpoint and add rationale.
