### ISSUE TITLE
SME_METADATA_AUTOPILOT_JOBS needs fix to meet length constraints

### ISSUE THREAD

**Issue by DirkatExasol** [exasol/sagemaker-extension#94]
When specifying problem_type und objective the trsining script raises the following error:  

[Code: 0, SQL State: 43000]  "E-SME-7: Error occurred in training with Sagemaker Autopilot: data exception - string data, right truncation; Valuelength: 22 Maxlength: 20 Value: '{ "MetricName": "F1" }'" caught in script "CREDIT"."SME_TRAIN_WITH_SAGEMAKER_AUTOPILOT" at line 189 (Session: 1775197807069429760)

**Comment by tkilias** [comment]
After a first analysis, we found that the UDF [SME_AUTOPILOT_TRAINING_UDF](https://github.com/exasol/sagemaker-extension/blob/3b938694feb79293d640e4a8f608f06c62438ea0/exasol_sagemaker_extension/resources/udf/create_statement_autopilot_training_udf.sql#L9) defines problem_type and objective only as VACHAR(20)
